ROOT = ..

RECURSIVE_TARGETS = test
DIRS = CodeSource FramePointers CompilerDriver ThreadLocal RetainedAdmission RetainedCode RelocationTypes EntryPublication HelloWorld CodeLayout libquantum bzip2

include $(ROOT)/common.mk
